### ISSUE TITLE
Alpine version completely stripped of most libraries

### ISSUE THREAD

**Issue by tsloughter** [c0b/docker-erlang-otp#57] opened 2017-07-07 21:13 UTC
Why does the alpine install of Erlang have everything removed?

It isn't possible to use it as a base image for building a release the way it is.

I'd also propose adding rebar3 to the image.

**Comment by c0b** [comment] 2017-07-07 21:27
what do you mean by `everything removed` ? at least it still has `erts` `kernel` `stdlib` `inets` I'd like call these as core erlang apps, built under `OTP_SMALL_BUILD=true`

I see most people use alpine images for production deployment, the minimum image size would be preferred over feature rich? 

with multi-stage build, you can still copy whatever from the default `erlang:20` as -dev image
https://docs.docker.com/engine/userguide/eng-image/multistage-build/#use-multi-stage-builds

**Comment by tsloughter** [comment] 2017-07-07 21:30
But isn't the point to be able to build something? With only those libs nothing works. Rebar3 won't even run because crypto is missing.

**Comment by tsloughter** [comment] 2017-07-07 21:32
I use multi-stage builds for creating production image but would expect that the Erlang image is capable of building my release on its own. As in, what I expected to work was:

```
FROM erlang:20.0.1-alpine as builder

WORKDIR /usr/src/app
COPY . /usr/src/app
RUN rebar3 as prod tar

RUN mkdir -p /opt/rel
RUN tar -zxvf /usr/src/app/_build/prod/rel/*/*.tar.gz -C /opt/rel

FROM alpine:3.6

RUN apk add --no-cache openssl-dev

WORKDIR /opt/presence

ENV RELX_REPLACE_OS_VARS true

ENV NODE 127.0.0.1
ENV PORT 8080
ENV DISCOVERY_DOMAIN localhost
ENV POSTGRES_HOST localhost
ENV POSTGRES_PORT 5432
ENV POSTGRES_DATABASE test
ENV POSTGRES_USER test
ENV POSTGRES_PASSWORD test

COPY --from=builder /opt/rel /opt/presence

EXPOSE 8080 8080

ENTRYPOINT ["/opt/presence/bin/presence"]
```

**Comment by c0b** [comment] 2017-07-11 18:54
from comments like https://github.com/c0b/docker-elixir/issues/1#issuecomment-312121446 I think a minimal image include erts (and kernel, stdlib, inets) is useful in some cases, for non-crypto related plain http/ftp networking applications, but based on the fact https is more common today, I agree that crypto should be included; the situation changed a lot since `OTP_SMALL_BUILD=true` was designed, maybe crypto should be part of OTP_SMALL_BUILD; or if not I'll add it into the minimal image.

**Comment by tsloughter** [comment] 2017-07-11 19:07
Ok, I don't agree or understand :) but have my own erlang-alpine image I'm using now for building releases for use in alpine, so ok with closing this issue.

**Comment by tsloughter** [comment] 2017-07-20 20:30
This came up again at work :). Do you use the alpine images? If not, I'm curious if you know someone who does, as I'd be interested to know their use case.

**Comment by tsloughter** [comment] 2017-07-20 20:33
I also noticed your comment:

> only for those Erlang apps written in C NIF, that could make sense, those can use the erlang:latest as builder, and copy to erlang:alpine for deployment

But that isn't the case since `latest` is debian.

**Comment by c0b** [comment] 2017-07-23 05:10
> This came up again at work :). Do you use the alpine images? If not, I'm curious if you know someone who does, as I'd be interested to know their use case.

the erlang images here were developed more following https://hub.docker.com/_/python/ or https://hub.docker.com/_/node/ 's model which has 3 series of images: the `latest` for `buildpack-deps` based, the `slim` for `debian` based, and `alpine` for alpine based, the releasing process of python or nodejs developed apps are a COPY of `requirements.txt` or `package.json` then followed by RUN `pip install` or `npm install`, then copy the app's code to a place (like /usr/src/app) in image and followed by CMD for how to run the app;
the benefits are: python standard library or nodejs core apis (https://nodejs.org/api/) would always be available, especially useful for debugging when need docker exec into, and may copy into a debugger script to run, in python or nodejs world, people assumes the standard library always available

the erlang way of release by systools or `rebar3 as prod tar` you mentioned, is counter-intuitive to most engineers with python or nodejs background, it's not copying my app to /usr/src/app, but instead it's copying my app code (compiled beam files) to `_build/prod/rel` and copy all dependencies like ERTS, kernel, stdlib, ... into it; the erlang runtime is copied/embedded into my app code's folder, there's some way of code analyzing, if my app didn't directly(or indirectly) call crypto, that crypto will not be copied, right? so at debugging time, some core apps might not be available?
(correct me if I misunderstand, this tool is not in use here)

In a polyglot environment, we're using the way more intuitive to most people with other language background, just package my app to a rpm/deb and use the Linux distro's way of packaging/deploying, that provided people assumption of:
1. python runtime (and its standard libraries) always at /usr/bin/python /usr/lib/pythonX.Y/...
2. node runtime (and its core apis libraries) always at /usr/bin/node /usr/lib/...
3. same thing applies to java, ruby, perl, ... and others
     java runtime always at /usr/bin/java symlink to /usr/java/jdk<version>/jre/bin/java
     perl runtime at /usr/lib/perl... with a symlink /usr/bin/perl
4. erlang runtime is treated same way as other languages:
     at /usr/lib/erlang/bin/erl ... /usr/lib/erlang/lib/<erlang standard libraries>

all app code developed in whatever language, can be deployed to /opt/appName-version/...

this way works well since many years ago when no docker/container yet; now with container the same way of deployment can still work well: just grab a `erlang:...` image and put app code under 
/opt/appName-version/...

why the erlang unique way need to embed ERTS/libs into user's app? it is one way of releasing but not the only way

however with discussions here, I realized that you want is a developer friendly (with gcc compiler and full erlang inlcuded), that for sure can be developed, would you like to checkout the already-done in #58 ? it's still not full (to save some image size) but can build rebar3 / elixir apps; to build a full erlang release is just remove the `OTP_SMALL_BUILD` and `EXTRA_APPLICATIONS`; I've build it locally, with gcc compiler uninstalled the image with full erlang alpine is about 60MB,

```diff
 	  && export OTP_SMALL_BUILD=true \
 +		EXTRA_APPLICATIONS='\
 +		  crypto public_key asn1 ssl \
 +		  erl_interface syntax_tools \
 +		  eunit dialyzer edoc snmp' \
```

the image size may not matter in a developer friendly image, then the erlang images should be more similar to the golang images: the `golang:alpine` are with gcc and go compiler, for image size at 268MB, then a gcc included erlang alpine can for sure be made at around that size

```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
golang              1.8                 6d9bf2aec386        2 weeks ago         698.6 MB
golang              latest              6d9bf2aec386        2 weeks ago         698.6 MB
golang              1.9                 e81ae2fb2728        2 weeks ago         718.6 MB
golang              1.9-rc              e81ae2fb2728        2 weeks ago         718.6 MB
golang              1.9-alpine          91cae16c7e05        3 weeks ago         268.6 MB
golang              1.9-rc-alpine       91cae16c7e05        3 weeks ago         268.6 MB
golang              rc-alpine           91cae16c7e05        3 weeks ago         268.6 MB
golang              1.8-alpine          310e63753884        3 weeks ago         257.1 MB
golang              alpine              310e63753884        3 weeks ago         257.1 MB
```

**Comment by tsloughter** [comment] 2017-07-23 16:25
I think Erlang's unique way actually maps really well to how to build docker images, particularly now with multi-stage builds. Or, I should say, it maps better than what other languages with a separate runtime, but essentially ends up being the same as you get with Go.

Because making the minimal copy of the runtime required for running your program is built in to Erlang you do not need a separate docker image. Instead, you have a situation like Go. You build your executable in a `golang:alpine` image and copy it into a base Alpine image. The same is done with Erlang, but instead of an executable it is a tarball.

I also am not sure why what is intuitive to Node, Python or Java programmers should be considered for Erlang images? Though they do seem intuitive to Go programmers -- and certainly to Erlang programmers, which should be the target audience.

---

Now, the idea of an image with just erts could be useful in one way, but still requires an image that has everything to work in tandem with it.

A release can be built to exclude erts but include the system libs (kernel, stdlib, crypto, etc) that are needed. So with an alpine image that contains everything you can build this release and copy it from that image to one that only has erts builtin. 

Doing that would save some space I guess on the top layer of of the image. But again, still requires the alpine image with everything that can be used to build your project, since you can't use the Debian image to do the build if you have dependencies with NIFs for example.

**Comment by c0b** [comment] 2017-08-14 22:06
> Erlang's unique way actually maps really well to how to build docker images, particularly now with multi-stage builds

there is still one difference between Erlang runtime and Go runtime is: the Go usually build into a single binary, the runtime is embedded (and smaller in size); Erlang runtime is closer to other dynamic language's runtime, can be separate from user's app, and usually bigger in size, one benefit to keep it separate in the docker image is to cache the layer, saves building time, and storage cost, especially to the privately operated docker registry. Because each So if the process can be like pip flows, it can re-uses cache better and saving development time; during erlang app development cycles, it's very probable that user's code changing more often than dependencies, move dependencies to beginning of the Dockerfile will be able to re-use cache better
https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#build-cache

    FROM erlang:20-alpine
    COPY dependencies    # some dependencies description file; similar to COPY requirements.txt in Python
    RUN ....             # compile dependencies; similar to pip install in Python
    COPY . /usr/src/app  # copy user app code
    RUN ....             # compile user app src code into beam; Python compiles *.py to *.pyc on the fly

the current `erlang:20-alpine` is a re-built one with full libraries of erlang distribution, include erlc compilers but not gcc compilers for size reasons. if users' code is known have NIF code, can add gcc on the fly (it seems most erlang libraries are pure Erlang?); hopefully can cover both use cases well, to `python:alpine` as a really slim erlang runtime, or as a builder like `golang:alpine` serves

    FROM FROM erlang:20.0.1-alpine as builder
    RUN apk add --no-cache gcc ...

**Comment by tsloughter** [comment] 2017-09-16 19:56
Oh, great, I missed this. I think this means I can start basing my images on this. I think NIFs are fairly common these days, but as you mention adding in the compiler with apk is easy enough.

I've wanted to fiddle with seeing how fast I can make building a new image. Right now we just let it rebuild the release from scratch. Not sure if there is a way to explicitly say 'cache everything under this directory as a layer'.

**Comment by tuncer** [comment] 2017-09-28 02:43
Not only are NIFs common, but since OTP 20 you could say `crypto` and `rand` are interdependent (http://erlang.org/doc/man/crypto.html#rand_seed-0). Also, I agree with @tsloughter that being able to use the compiler and the rest of the "core" libs is a common thing to do for many Erlang projects. Writing a Yaws website is enough to require `compiler`.

So, how about turning the existing alpine image into alpine-slim or adding alpine-full?

**Comment by tuncer** [comment] 2017-09-28 02:58
I've been able to use the compiler and Dialyzer and crypto with `20.1-alpine`, so has the issue of missing apps been resolved?

**Comment by c0b** [comment] 2017-09-28 03:24
yes; after #78 the library issues should have been resolved, so I can close this now (but remains open if anyone found other library issues can still file a new one)

the alpine-full and alpine-slim could lead to another direction but are you sure you want that?
basically, it's a maintenance issue: for an erlang image, at least we maintain different erlang versions, then multiple number of OSes, in the past was debian-jessie based, right this year more images are adding debian-stretch support, some others have alpine3.6 alpine3.5 alpine3.4 ... and more variants, are you sure want alpine3.6-full and alpine3.5-slim? the maintenance is a permutation of all these factors
https://hub.docker.com/_/erlang/ (it's 9 variants right now, I think ideally keep it under 10)

**Closed by c0b** 2017-09-28 03:24 UTC
